/* Scripted Pipeline */
node() {
    try {
        stage('Build') {
            docker.image('python:3.10.1-alpine').inside {
                sh 'python -m py_compile sources/add2vals.py sources/calc.py'
        } 
        }
    } catch (e) {
        echo 'This will run only if successful'

        throw e
    } finally {
        // Post steps in here i guess
    }
    
}


node() {
    try {
        stage('Test') {
            docker.image('qnib/pytest').inside {
                sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
        } 
        }
    } catch (e) {
        echo 'This will run only if successful'

        throw e
    } finally {
        // Post steps in here i guess
    }
    
}
