/* Scripted Pipeline */
node('docker') {
    try {
        stage('Build') {
            docker.image('python:3.10.1-alpine').inside {
                sh 'python -m py_compile sources/add2vals.py sources/calc.py'
        } 
        }
    } catch (e) {
        echo 'This will run only if successful'

        throw e
    } finally {
        // Post steps in here i guess
    }
    
}